# Generated by Django 3.2.8 on 2023-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230608_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
